Add box to tell owner/superuser certain model details are only visible to them
brain-score/brain-score.web pull request #119
Opened 2021-12-13 20:07 UTC by mike-ferguson

2021-12-13 20:12 UTC, mschrimpf requested changes
`div.visible-to-owner` reinvents the wheel, use e.g. https://bulma.io/documentation/elements/box/

2021-12-13 21:02 UTC, mschrimpf commented
can you please post a screenshot of what the site looks like with this change?

2021-12-13 21:05 UTC, mschrimpf requested changes

2021-12-13 21:05 UTC, mschrimpf commented on benchmarks/templates/benchmarks/model.html
>          {% if model.reference_identifier %}
can we please also move this above the fine-print? I.e. have: 
```
<model name>
<reference link>
```

and then the details?

2021-12-13 21:05 UTC, mschrimpf commented on benchmarks/templates/benchmarks/model.html
>          <span class='information'>Model Name:</span> {{ model.name }}<br>
remove, `model.name` is already the title

2021-12-13 21:05 UTC, mschrimpf commented on benchmarks/templates/benchmarks/model.html
>          <span class='information'>Reference Link:</span>
remove this span, let's just have the link

2021-12-15 15:48 UTC, mike-ferguson commented
Screenshot
<img width="1384" alt="Screen Shot 2021-12-15 at 10 40 52 AM" src="https://user-images.githubusercontent.com/38020092/146218565-c5486c9c-3a8b-45ee-8690-046d46c2e1e5.png">
:

2021-12-15 17:00 UTC, mschrimpf requested changes

2021-12-15 21:50 UTC, mschrimpf reviewed
almost done

2021-12-15 21:50 UTC, mschrimpf commented on benchmarks/templates/benchmarks/model.html
> +        <p class="no_reference">No reference paper on file.</p>
delete

2021-12-15 21:50 UTC, mschrimpf commented on web/settings.py
> +ALLOWED_HOSTS = [os.getenv("DOMAIN", "localhost:brain-score-web-dev.us-east-2.elasticbeanstalk.com").split(":"), "127.0.0.1"]
undo this change (fine to keep locally, but not on prod)

2021-12-16 02:45 UTC, mschrimpf commented on benchmarks/templates/benchmarks/model.html
> +    {% else %}
delete the `else` too

2021-12-21 14:34 UTC, mschrimpf approved these changes

2021-12-21 15:44 UTC, merged